### ISSUE TITLE
并查集-Union-Find：完整模板代码处有一处小的方法名错误

### ISSUE THREAD

**Issue by Crazyokd** [LFool/LFool-Notes#1]
如下：`conneted` 应为 `connected`
<img width="296" alt="image" src="https://user-images.githubusercontent.com/74645100/182846486-827729dd-21b0-437e-b5c6-b8ae72f2861f.png">

**Comment by LFool** [comment]
> 如下：`conneted` 应为 `connected` <img alt="image" width="296" src="https://user-images.githubusercontent.com/74645100/182846486-827729dd-21b0-437e-b5c6-b8ae72f2861f.png">

收到，已经修改过来啦！感谢 🙏
