### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by limits220284** [LFool/LFool-Notes#2]
您好，请问您这个项目是怎么搭建成的，主要是md文件到html这一步是通过什么来完成的？感谢您的回答

**Comment by LFool** [comment]
我是使用 Typora 这个软件写 Markdown 笔记，然后软件自带可以导出成 html，还可以去 typora 官网下载喜欢的主题

**Comment by LFool** [comment]
@limits220284 

我是使用 Typora 这个软件写 Markdown 笔记，然后软件自带可以导出成 html，还可以去 typora 官网下载喜欢的主题

**Comment by limits220284** [comment]
> @limits220284
> 
> 我是使用 Typora 这个软件写 Markdown 笔记，然后软件自带可以导出成 html，还可以去 typora 官网下载喜欢的主题

非常感谢！已star
