### ISSUE TITLE
回文子串的两种方法-中心扩展-动态规划的帖子中 动态规划

### ISSUE THREAD

**Issue by zzdpk2** [LFool/LFool-Notes#3]
你好, "当我们判断[i..j]是否为回文子串时，只需要判断s[i] == s[j]，同时判断[i-1..j-1]是否为回文子串即可"是不是应该改成"当我们判断[i..j]是否为回文子串时，只需要判断s[i] == s[j]，同时判断**[i +1**..j-1]是否为回文子串即可"?

**Comment by LFool** [comment]
是的，你是对的，我写的有问题，十分感谢你～
