### ISSUE TITLE
大佬有个数据库锁的问题没有明白，帮忙解答下。【MySQL加锁实战分析】

### ISSUE THREAD

**Issue by EastEightAreaBoy** [LFool/LFool-Notes#4]
【MySQL加锁实战分析】文章中的内容有个我实践下来不太理解。
![image](https://github.com/LFool/LFool-Notes/assets/16572649/4fc243a6-dc56-4dc6-8512-3ead9c014a96)
上面是我的表信息。
age是一个普通索引。我执行sql：select * from `mvcc-test1` where age = 21 for update;后我理解就不能再插入age是20-30之间的数据了对吧？可是我在单独开一个控制台后执行插入却成功了。

# 这个是我加锁的命令。
![image](https://github.com/LFool/LFool-Notes/assets/16572649/192e3d35-3e21-4d1e-8e1a-947f350c56b3)
这个是我插入的数据。
![image](https://github.com/LFool/LFool-Notes/assets/16572649/2727a516-c095-4de3-b89a-4eba9fe04fcf)

**Comment by LFool** [comment]
@EastEightAreaBoy 

我模拟了一下你的过程，我这边第开启的二个插入事务是被卡住的呀！！

<img width="1286" alt="image" src="https://github.com/LFool/LFool-Notes/assets/36959740/995cbbc4-2cee-482f-9899-a17464d3e3ec">

**Comment by LFool** [comment]
@EastEightAreaBoy 

我的数据库版本是 MySQL 8.0.33

我模拟了一下你的过程，我这边第开启的二个插入事务是被卡住的呀！！

<img width="1171" alt="image" src="https://github.com/LFool/LFool-Notes/assets/36959740/807a9394-389b-408f-881d-50060621b39a">

**Comment by EastEightAreaBoy** [comment]
是我使用的工具问题。即使开的不同的窗口但是事务id却是一个。
![image](https://github.com/LFool/LFool-Notes/assets/16572649/808cd624-90c7-4ac6-bf14-db2932cddcda)

**Comment by EastEightAreaBoy** [comment]
是我使用的工具问题。开的不同窗口但是事务id是一个。
![image](https://github.com/LFool/LFool-Notes/assets/16572649/f05097f6-fee1-477c-b427-3a183650b79b)

**Comment by EastEightAreaBoy** [comment]
是我工具的问题，不同的窗口都是同一个事务。
![image](https://github.com/LFool/LFool-Notes/assets/16572649/a590849d-a48b-475e-9be9-9c08f1768b8d)
